### ISSUE TITLE
TODO List for 6.5.0 Release.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#3610]
**Description:**

- [x]  Update the product.txt file

- [x]  Make sure all the read me files are updated

- [x]  Update the release notes

- [x]  Check for the duplicate jars in the plugins directory

- [x]  Update all the html files and link

- [x]  Check for no existence of SNAPSHOT versions or Mile Stone Version

- [x]  https://github.com/wso2/product-ei/issues/3609

- [ ] Create p2 repository 

- [ ]  Performance comparison with previous release

- [x]  https://github.com/wso2/product-ei/issues/3719
