### ISSUE TITLE
Upgrade Dependency Versions

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#4321]
- [ ] Bump maven-scr-plugin from 1.7.2 to 1.26.2 #4100
- [ ] org.springframework.version from 4.1.5.RELEASE to 5.1.7.RELEASE #4098 
- [ ] com.fasterxml.jackson.core.version from 2.9.8 to 2.9.9 #4097
- [ ] maven-assembly-plugin from 2.5.3 to 3.1.1 #3834
- [ ] antlr4-runtime from 4.5.1.wso2v1 to 4.6.wso2v1 #3833
- [ ] maven-project-info-reports-plugin from 2.4 to 3.0.0 #3832
- [ ] httpcore from 4.3.0.wso2v1 to 4.3.3.wso2v1 #3830

## Carbon Mediation repository

- [ ] org.eclipse.osgi from 3.7.0.v20110613 to 3.9.1.v20140110-1610 wso2/carbon-mediation#1276
- [ ] axiom-api from 1.2.11.wso2v13 to 1.2.22 wso2/carbon-mediation#1275
- [ ] axis2-transport-base from 1.6.1-wso2v35 to 1.7.9 wso2/carbon-mediation#1274
- [ ] activemq-broker from 5.15.2 to 5.15.9 wso2/carbon-mediation#1273
- [ ] carbon.deployment.version from 4.8.3 to 4.8.5 wso2/carbon-mediation#1272
- [ ] netty.version from 4.0.39.Final to 4.1.36.Final wso2/carbon-mediation#1228
- [ ] maven-bundle-plugin from 2.3.5 to 4.2.0 wso2/carbon-mediation#1227
- [ ] httpcore from 4.3.3 to 4.4.11 wso2/carbon-mediation#1225

## Synapse repository

- [ ] quartz from 2.1.1 to 2.3.1 wso2/wso2-synapse#1362
- [ ] mina-core from 1.1.0 to 2.1.2 wso2/wso2-synapse#1361
- [ ] org.jacoco.ant from 0.7.9 to 0.8.4 wso2/wso2-synapse#1360
- [ ] httpcore from 4.3.3 to 4.4.11 wso2/wso2-synapse#1359
- [ ] spring.version from 1.2.8 to 5.1.7.RELEASE wso2/wso2-synapse#1358
- [ ] activation from 1.1 to 1.1.1 wso2/wso2-synapse#1337 

## Carbon Data repository

- [ ] bson4jackson from 2.9.0 to 2.9.2 wso2/carbon-data#275
- [ ] maven-dependency-plugin from 2.10 to 3.1.1 wso2/carbon-data#274
- [ ] netty.version from 4.0.39.Final to 4.1.36.Final wso2/carbon-data#273
- [ ] maven-antrun-plugin from 1.1 to 1.8 wso2/carbon-data#272
- [ ] maven-source-plugin from 2.1.2 to 3.1.0 wso2/carbon-data#271
- [ ] wagon-ssh from 2.1 to 3.3.2 wso2/carbon-data#263
- [ ] mysql-connector-java from 5.1.35 to 8.0.16 wso2/carbon-data#262
- [ ] build-helper-maven-plugin from 1.7 to 3.0.0 wso2/carbon-data#261

**Comment by jvkassi** [comment]
Hello,

is it possible to upgrade spring to at least 4.x 
We need this to support Elastic APM. 
https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-web-frameworks

**Comment by jvkassi** [comment]
Hello @a5anka, can you help ?

**Comment by jvkassi** [comment]
Hello, 

Is it possible ? @a5anka @malakaganga

**Comment by a5anka** [comment]
Adding @arunans23
