### ISSUE TITLE
TODO list for 6.6.0 release

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4710]
**Description:**

- [x]  Update the product.txt file

- [x]  Make sure all the read me files are updated

- [x]  Update the release notes

- [x]  Check for the duplicate jars in the plugins directory

- [x]  Update all the html files and link

- [x]  Check for no existence of SNAPSHOT versions or Mile Stone Version

- [x]  https://github.com/wso2/product-ei/issues/3609

- [x] Create p2 repository 

- [ ]  Performance comparison with previous release

- [ ]  https://github.com/wso2/product-ei/issues/3719

- [ ] Migration guide
